#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check packages installed and node versions
npm install ||
(
    echo '❌😤🤢🤮❌ NPM install failed. Please check your node version or package versions.
            Use 
                npm install -g n
                n X.X.X
            to install the required node version.'
    false;
)

# If everything passes... Now we can check coding standards
echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to verify code standards now. 🤔🤔🤔🤔'

# Check Prettier standards
npm run check-format ||
(
    echo '🤢🤮🤢🤮 Prettier Check Failed. Run npm run format, add changes and try to stage and commit again.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
    echo '😤🏀👋😤 ESLint Check Failed. Make the required changes listed above, add changes and try to stage and commit again.'
    false; 
)

# If everything passes... Now we can build
echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

npm run check-build ||
(
    echo '❌👷🔨❌ Next build failed: View the errors above to see why.'
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'